#!/usr/bin/env -S node --import tsx

/**
 * Initialize a fresh Zuhn knowledge base.
 * Run this after cloning the repo to create an empty KB structure
 * without any existing knowledge content.
 *
 * Usage: node --import tsx scripts/init.ts [--force]
 *   --force  Overwrite existing knowledge-base directory
 */

import { existsSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";

const PROJECT_ROOT = join(__dirname, "..");
const KB_ROOT = join(PROJECT_ROOT, "knowledge-base");

const force = process.argv.includes("--force");

// ─── Safety check ─────────────────────────────────────────────────────

if (existsSync(join(KB_ROOT, "domains")) && !force) {
  const domainFiles = require("node:fs")
    .readdirSync(join(KB_ROOT, "domains"), { recursive: true })
    .filter((f: string) => f.endsWith(".md"));

  if (domainFiles.length > 0) {
    console.error("Error: knowledge-base/domains/ already contains files.");
    console.error("       Use --force to overwrite, or manually clear the directory.");
    console.error(`       Found ${domainFiles.length} existing files.`);
    process.exit(1);
  }
}

// ─── Create directory structure ───────────────────────────────────────

const dirs = [
  "domains",
  "principles",
  "mental-models",
  "tensions",
  "sources/youtube",
  "sources/youtube/raw",
  "sources/blog",
  "sources/reddit",
  "sources/pdf",
  "sources/audio",
  "sources/paste",
  "decisions",
  "predictions",
  "archive/stale",
  "archive/superseded",
  "archive/low-value",
  "tags",
  "views",
  "meta",
  "db",
];

console.log("Creating Zuhn knowledge base structure...\n");

for (const dir of dirs) {
  const fullPath = join(KB_ROOT, dir);
  mkdirSync(fullPath, { recursive: true });
  console.log(`  mkdir ${dir}/`);
}

// ─── Create starter files ─────────────────────────────────────────────

// MASTER_INDEX.md
writeFileSync(
  join(KB_ROOT, "MASTER_INDEX.md"),
  `# Zuhn Knowledge Base

> Start by ingesting content: \`npm run ingest <url>\`

## Domains
No domains yet. Domains are created automatically when you extract insights.

## Quick Links
- [Flags](meta/flags.md) — learning mechanism outputs
- [Stats](meta/stats.md) — knowledge base statistics
`
);
console.log("  write MASTER_INDEX.md");

// meta/flags.md
writeFileSync(
  join(KB_ROOT, "meta/flags.md"),
  `# Learning Layer Flags
Generated by learn.ts

## COMPRESS
None.

## DISCOVER
None.

## GAP
None.

## TRANSFER
None.
`
);
console.log("  write meta/flags.md");

// meta/stats.md
writeFileSync(
  join(KB_ROOT, "meta/stats.md"),
  `# Knowledge Base Stats

> Generated: ${new Date().toISOString().slice(0, 10)}

- **Total insights:** 0
- **Domains:** 0
- **Topics:** 0
- **Tags:** 0
`
);
console.log("  write meta/stats.md");

// meta/pending-urls.txt
writeFileSync(join(KB_ROOT, "meta/pending-urls.txt"), "\n");
console.log("  write meta/pending-urls.txt");

// tags/_index.md
writeFileSync(
  join(KB_ROOT, "tags/_index.md"),
  `# Tag Index

No tags yet. Tags are created automatically during insight extraction.
`
);
console.log("  write tags/_index.md");

// sources/_index.md
writeFileSync(
  join(KB_ROOT, "sources/_index.md"),
  `# Source Index

No sources yet. Run \`npm run ingest <url>\` to add your first source.
`
);
console.log("  write sources/_index.md");

// .gitkeep files for empty dirs that git needs to track
const gitkeepDirs = ["decisions", "predictions", "mental-models", "tensions", "archive/stale"];
for (const dir of gitkeepDirs) {
  writeFileSync(join(KB_ROOT, dir, ".gitkeep"), "");
}

// ─── Bundled sample source ──────────────────────────────────────────
const sampleSource = `---
id: SRC-000000-DEMO
type: paste
title: 'The Spacing Effect: Why Distributed Practice Beats Cramming'
date_ingested: '${new Date().toISOString().slice(0, 10)}'
insight_count: 0
word_count: 195
---
Research consistently shows that distributed practice dramatically outperforms massed practice for long-term retention. Students who space their study sessions across multiple days retain two to three times more material than those who cram the same total hours into a single session.

The mechanism appears to be retrieval difficulty: when you revisit material after a delay, the slight effort of recalling it strengthens the memory trace. This is counterintuitive because spaced practice feels harder and less productive in the moment, even though it produces superior long-term results.

The spacing effect applies beyond academic study. Companies that ship features in small, frequent releases build more institutional knowledge than those shipping large quarterly releases. Musicians who practice scales for ten minutes daily improve faster than those who practice seventy minutes once a week.

The optimal spacing interval grows with expertise: beginners benefit from daily review, while experts may need only monthly refreshers. The Leitner system exploits this by sorting flashcards into boxes with increasing review intervals based on recall accuracy.

One practical implication: if you can only do one thing to improve learning, don't change what you study — change when you study it.
`;
writeFileSync(join(KB_ROOT, "sources/paste/sample-spacing-effect.md"), sampleSource);
console.log("  write sources/paste/sample-spacing-effect.md (SRC-000000-DEMO)");

console.log("\n✓ Knowledge base initialized.");
console.log("\nNext steps:");
console.log("  1. Open Claude Code and say: extract insights from SRC-000000-DEMO");
console.log("  2. npm run search \"spacing effect\"");
console.log("  3. Optional: ollama pull nomic-embed-text (for semantic search)");
console.log("  4. Optional: npm run ingest <url> (YouTube, blogs, PDFs)");
console.log("");
