#!/usr/bin/env npx tsx

import { join } from "node:path";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import {
  scanInsights,
  buildMasterIndex,
  buildDomainOverview,
  buildTopicSummary,
  buildTagIndex,
} from "./lib/generate-index.js";
import type { ParseSuccess } from "./lib/parse-insight.js";
import { initDb, upsertInsight, getAllInsights } from "./lib/db.js";

const KB_ROOT = join(__dirname, "../knowledge-base");

// ─── Helpers ──────────────────────────────────────────────────────────

/** Write file only if content has actually changed. Returns true if written. */
async function writeIfChanged(filePath: string, content: string): Promise<boolean> {
  try {
    const existing = await readFile(filePath, "utf-8");
    if (existing === content) return false;
  } catch {
    // File doesn't exist yet — will write
  }
  await mkdir(join(filePath, ".."), { recursive: true });
  await writeFile(filePath, content, "utf-8");
  return true;
}

/** Mark an insight file as indexed: true by string-replacing the frontmatter flag. */
async function markIndexed(filePath: string): Promise<void> {
  const raw = await readFile(filePath, "utf-8");
  if (raw.includes("indexed: false")) {
    const updated = raw.replace("indexed: false", "indexed: true");
    await writeFile(filePath, updated, "utf-8");
  }
}

// ─── Main ─────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log("=== reindex.ts ===");
  console.log(`Scanning: ${KB_ROOT}`);

  // 1. Scan insights
  const insights = await scanInsights(KB_ROOT);

  if (insights.length === 0) {
    console.log("0 valid insights found. Nothing to index.");
    return;
  }

  console.log(`Found ${insights.length} valid insights.`);

  let filesWritten = 0;

  // 2. Build and write MASTER_INDEX.md
  const masterContent = buildMasterIndex(insights);
  if (await writeIfChanged(join(KB_ROOT, "MASTER_INDEX.md"), masterContent)) {
    filesWritten++;
    console.log("  Updated: MASTER_INDEX.md");
  }

  // 3. Group insights by domain and topic
  const domainMap = new Map<string, ParseSuccess[]>();
  const topicMap = new Map<string, Map<string, ParseSuccess[]>>();

  for (const ins of insights) {
    const d = ins.data.domain;
    const t = ins.data.topic;

    // Domain grouping
    if (!domainMap.has(d)) domainMap.set(d, []);
    domainMap.get(d)!.push(ins);

    // Topic grouping (nested under domain)
    if (!topicMap.has(d)) topicMap.set(d, new Map());
    const topics = topicMap.get(d)!;
    if (!topics.has(t)) topics.set(t, []);
    topics.get(t)!.push(ins);
  }

  // 4. Domain overviews
  for (const [domain, domainInsights] of domainMap) {
    const overviewPath = join(KB_ROOT, "domains", domain, "_overview.md");
    const content = buildDomainOverview(domain, domainInsights);
    if (await writeIfChanged(overviewPath, content)) {
      filesWritten++;
      console.log(`  Updated: domains/${domain}/_overview.md`);
    }
  }

  // 5. Topic summaries
  for (const [domain, topics] of topicMap) {
    for (const [topic, topicInsights] of topics) {
      const summaryPath = join(KB_ROOT, "domains", domain, topic, "_summary.md");
      const content = buildTopicSummary(topic, topicInsights);
      if (await writeIfChanged(summaryPath, content)) {
        filesWritten++;
        console.log(`  Updated: domains/${domain}/${topic}/_summary.md`);
      }
    }
  }

  // 6. Tag files
  const tagIndex = buildTagIndex(insights);
  const tagsDir = join(KB_ROOT, "tags");
  await mkdir(tagsDir, { recursive: true });

  for (const [tag, content] of tagIndex) {
    const tagPath = join(tagsDir, `${tag}.md`);
    if (await writeIfChanged(tagPath, content)) {
      filesWritten++;
      console.log(`  Updated: tags/${tag}.md`);
    }
  }

  // 7. Tags _index.md
  const tagNames = [...tagIndex.keys()].sort();
  const tagIndexLines: string[] = [
    "# Tags Index",
    "Generated by reindex.ts. Do not edit manually.",
    "",
  ];
  for (const tag of tagNames) {
    tagIndexLines.push(`- [${tag}](./${tag}.md)`);
  }
  tagIndexLines.push("");
  if (await writeIfChanged(join(tagsDir, "_index.md"), tagIndexLines.join("\n"))) {
    filesWritten++;
    console.log("  Updated: tags/_index.md");
  }

  // 8. Mark unindexed insights as indexed
  let markedCount = 0;
  for (const ins of insights) {
    if (!ins.data.indexed) {
      await markIndexed(ins.filePath);
      markedCount++;
    }
  }
  if (markedCount > 0) {
    console.log(`  Marked ${markedCount} insights as indexed: true`);
  }

  // 9. Stats file
  const domains = [...domainMap.keys()];
  const allTopics = new Set<string>();
  for (const topics of topicMap.values()) {
    for (const t of topics.keys()) allTopics.add(t);
  }

  const statsLines: string[] = [
    "# Knowledge Base Stats",
    "",
    `> Generated: ${new Date().toISOString().slice(0, 10)}`,
    "",
    `- **Total insights:** ${insights.length}`,
    `- **Domains:** ${domains.length}`,
    `- **Topics:** ${allTopics.size}`,
    `- **Tags:** ${tagIndex.size}`,
    "",
  ];
  const statsPath = join(KB_ROOT, "meta", "stats.md");
  await mkdir(join(statsPath, ".."), { recursive: true });
  if (await writeIfChanged(statsPath, statsLines.join("\n"))) {
    filesWritten++;
    console.log("  Updated: meta/stats.md");
  }

  // 10. Populate SQLite database
  console.log("\n--- SQLite database ---");
  const db = initDb();

  let dbInserted = 0;
  let dbUpdated = 0;

  // Collect all current IDs from the file system
  const currentIds = new Set<string>();

  for (const ins of insights) {
    currentIds.add(ins.data.id);

    // Check if this insight already exists in the DB
    const existing = db
      .prepare("SELECT content_hash FROM insights WHERE id = ?")
      .get(ins.data.id) as { content_hash: string } | undefined;

    upsertInsight(db, ins.data, ins.filePath);

    if (existing) {
      dbUpdated++;
    } else {
      dbInserted++;
    }
  }

  // Remove DB rows whose IDs no longer exist in the file system
  const allDbRows = getAllInsights(db);
  let dbDeleted = 0;
  const deleteStmt = db.prepare("DELETE FROM insights WHERE id = ?");

  for (const row of allDbRows) {
    if (!currentIds.has(row.id)) {
      deleteStmt.run(row.id);
      dbDeleted++;
    }
  }

  console.log(
    `  DB: ${dbInserted} inserted, ${dbUpdated} updated, ${dbDeleted} deleted`
  );
  console.log(`  Total rows: ${getAllInsights(db).length}`);
  db.close();

  console.log(`\nDone. ${filesWritten} files written.`);
}

main().catch((err) => {
  console.error("reindex.ts failed:", err);
  process.exit(1);
});
